public/manifest.json
manifest.jsonにデフォルト値である「React App」の文字が入っている。
このmanifest.jsonは表層に出ないものの、アクセス者にダウンロードされるため、適切な文字に変更する
React APP -> DRIP
Create React App Sample -> DRIP - Drecom Invention Project
に変更する。
=> fix: manifest.jsonにReactAppの文字があったため、これをDRIPに変更しておく

.env
#18 
*.jsに対して*.mapファイルがビルド時に生成されてしまう。
*.mapは逆コンパイルできてしまうため、基本的には削除したい
https://code-log.hatenablog.com/entry/2019/03/18/111559
`.env`ファイルを生成して、生成されないように設定文を書き加える
=> add: .envファイルを追加し、*.jsファイルに対して*.mapファイルが生成されないように設定文を追加

src/components/Team/Team.scss
close #60 
開発環境からコピーし忘れコードを写してくる
https://github.com/drip-pages/drip-official-dev/commit/de87c5f95791b032858293e870a75176670c3bf0
のコピペ
=> fix: safariでもメンバーがセンタリングするように

package.json, src/App.tsx, src/actions/header.tsx, src/components/HamburgerButton/HamburgerButton.scss, src/components/HamburgerButton/index.tsx, src/components/Header/index.tsx, src/index.tsx, src/pages/Home/index.tsx, src/pages/News/index.tsx, src/reducers/header.tsx, src/reducers/index.tsx, yarn.lock
close #48 
reactのstateだけでは状態管理が煩雑になり厳しい。
そこで、reduxを導入する。
reduxを導入し、必要なディレクトリ構造の作成を行う。
また、テストとして、ヘッダーのアコーディオンメニューを開くか開かないかをReduxに持たせる
=> add: reduxの導入

.gitignore
https://github.com/drip-pages/drip-official/issues/51
にてbashファイルを書くにあたって、
gh-pagesにプッシュしたくないディレクトリを.gitignoreレベルで排除しておきたい。
gh-pagesが管理している.gitignoreにgh-pagesにプッシュしたくないディレクトリを追記する。
=> add: gitignoreの更新

src/components/Header/Header.scss, src/components/Header/index.tsx
close #42 
アコーディオンメニューが開いている時、アコーディオンメニューの外をタッチしたら消えて欲しい。
アコーディオンメニューの下に不可視のタッチ判定を作成し、タッチされたらメニューを消すようにする
=> add: アコーディオンメニュー以外の部分をタッチした時に消えるようにする

src/components/Header/index.tsx
close #46 
アコーディオンメニューを開いたまま、ウィンドウサイズを大きくすると、アコーディオンメニューが閉じない。
ウィンドウサイズが一定の大きさを超えたら、アコーディオンメニューは閉じて欲しい
ウィンドウサイズの変更の検知を受け取り、Headerのハンバーガーボタン表示の閾値を超えたら消すようにした。
=> add: ウィンドウサイズが変わったらアコーディオンメニューを閉じる

src/App.tsx, src/actions/translator.tsx, src/components/Header/index.tsx, src/containers/Translator.tsx, src/pages/Home/index.tsx, src/reducers/index.tsx, src/reducers/translator.tsx, src/types/language.ts
close #50 
/enなど言語切り替え周りのコードが読みづらい
# 解決手法
Reduxを導入したため、現在表示している言語をReduxStateに保たせる。
これにより保守性と可読性を上げる
=> change: /enをRedux用にコード改変する

src/components/Invention/index.tsx
close #55 
Invention/index.tsxは全てのプロダクトが共通して使うはずなのにalt属性にAROWの文字があるのはおかしい
当たり障りないものに変更
=> fix: altにあった文字列を正しいものに変更

package.json
/enページにアクセスするとimg/icon.pngが404エラーしている。
最初にアクセスされる/en/index.htmlで呼び出されているicon.pngだが、/enディレクトリ下には/imgディレクトリが存在しない。
そこで、/imgを/en/imgにコピーすることで回避する
=> fix: icon.pngが404errorしないようにビルド時にimgディレクトリをコピーするようにした

src/containers/Translator.tsx
close #80 
/en/にダイレクトアクセスすると日本語のページが出ている。
本来は英語のページが表示される必要がある。
条件文に/enだけでなく/en/も英語に遷移するように変更する
=> fix: /en/でも英語のページを表示するように変更

src/components/Header/index.tsx, src/containers/Translator.tsx
close #83 
言語が切り替わった時にもアコーディオンメニューを閉じる
元々そうだったのに、切り替わってなかった
言語の切り替わりをチェックするTranslatorにてメニューを閉じる処理を追加する
=> fix: /enや/(日本語)に遷移した時もアコーディオンメニューを閉じる

src/containers/Translator.tsx
close #87 
newsページで英語ボタンを押すと英語のページに行かない
TranslatorでdidUpdateにてページ遷移検知と言語切り替えをしていたが、
他のコンポーネントがrenderされた後に呼ばれていた。
そこでWillUpdateにて処理をするように変更した
=> fix: 全てのrenderが走る前に言語切り替えの処理を走らせるように変更

package.json, yarn.lock
close #98
Githubからきたsecurity alertsに対応する
3つのパッケージをupgradeするため
yarn auditで脆弱性のあるパッケージの確認を行った
`npm ls eslint`
`yarn audit`
`yarn upgrade react-scripts`
などを使って解決
=> pacakge upgradeを行う

README.md
デプロイする際に、ページを構成するのに必要なファイルをstagingにあげず、commit,pushしてしまった。
その再発防止策としてREADMEのデプロイ手順のところに手順（注意書きとして）載せる
=> READMEにデプロイ時の手順を追記する

src/data/language/en.json, src/data/language/ja.json
close #112 
タイトル部分にある2020年のところを2021年に変更したい
文言を管理している
- src/data/language/en.json
- src/data/language.ja.json
編集
before
after
=> change: 2020年のところを2021に変更する

src/components/NewsList/NewsList.scss
close #125 
NEWSページの右側にスペースが欲しい
- NEWSページの右側にmargin-right: 40pxを追加
before
after
=> ニュース欄の右側に40pxのスペース追加する

src/components/ContactUs/ContactUs.scss, src/components/Footer/index.tsx, src/components/Member/Member.scss, src/components/Team/Team.scss, src/pages/Home/index.tsx
close #122 
DRIPページのデザインを変更したい
- Contact us の下に Teamセクションを置くようにする
- Teamの画像を240px->120pxに変更する
- Copyrightをドリコムofficialに合わせる（© Drecom Co.,Ltd. All rights Reserved.）
- Contact usの背景を白に、Teamの背景をグレーにする
- Contact usの上に2pxのグレーborderを追加する
=> DRIPページのデザイン変更

src/components/ContactUs/ContactUs.scss
#122 
#122 の変更点では、ContactUsの部分に当てるborderは上にだけ当てる必要があったので修正する
わかりづらいので、色つけ状態でスクリーンショットです。
before
after
=> change: topにのみborderを当てる

.github/workflows/gh-pages.yml, README.md
GitHub Actionsを利用してデプロイを走らせるためだけのPRです。
ユーザー影響はありません。
本PRをマージすることでGitHub Actionsが動き出し、デプロイ作業を実施してくれるはずです。
- https://github.com/drip-pages/drip-official/pull/137 GitHub Actionsを利用してデプロイ実施するようにする
もし、ページが表示されないなどの問題が発生した場合は、バックアップしているファイルをgh-pagesに入れるPRを作成して、元に戻します。
=> 本番更新2021/9/15 16:30

.github/workflows/gh-pages.yml
#136 
デプロイは成功したが、カスタムドメインが外れてしまった。
詳細は以下を参照
https://github.com/drip-pages/drip-official/issues/136#issuecomment-919780594
デプロイするときにカスタムドメインを設定して欲しい
https://qiita.com/peaceiris/items/d401f2e5724fdcb0759d
https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-add-cname-file-cname
を参考に`cname`を設定する。
別のリポジトリで試してみたところうまく設定されていることを確認した。
▼テスト時のPR
https://github.com/fukui-takanori/ogp-tester/pull/5/files
▼別リポジトリの設定ページ
https://github.com/fukui-takanori/ogp-tester/settings/pages
=> gh-pages.ymlのDeployジョブにcnameを追加する
